# render.yaml
services:
- type: web
  name: resumeapi
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz && python ./app.py
  # --- ADD SYSTEM PACKAGES HERE ---
  autoDeploy: true
  plan: starter
  numInstances: 1
  previewsEnabled: true
  disk:
    name: resume-disk
    mountPath: /var/data
  
  # Crucial for fixing BLIS/Spacy build errors
  buildPacks:
    - python
    - name: apt
      packages:
        - build-essential
        - python3-dev
